### ISSUE TITLE
Cannot compile statically

### ISSUE THREAD

**Issue by foi** [j8r/dockerfiles#4]
Hi!
Simple project with src/test.cr

```
require "llvm/lib_llvm"
require "llvm/enums"

puts "123"
```
Execute: **docker run --rm -it -v $PWD:/app -w /app jrei/crystal-alpine crystal build --static --release src/test.cr**
and gets:
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lstdc (this usually means you need to install the development package for libstdc)++
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/app/test'  -rdynamic -static  `/usr/bin/llvm-config --libs --system-libs --ldflags --link-static 2> /dev/null` -lstdc++ /usr/lib/libpcre.a /usr/lib/libgc.a /usr/lib/libpthread.a /usr/lib/crystal/core/ext/libcrystal.a /usr/lib/libevent.a /usr/lib/librt.a -L/usr/lib -L/usr/local/lib`

And i think docker project page have broken description 
![DeepinScreenshot_select-area_20190714152822](https://user-images.githubusercontent.com/26715/61181148-42cd8000-a64c-11e9-9b11-0ac77f62d420.png)

**Comment by j8r** [comment]
Thanks @foi. `g++` was removed because a C++ compiler wasn't needed, but `libstdc++.a` is present on this package. I can create a PR to https://github.com/alpinelinux/aports to move to a dedicated `libstdc++-dev` package.
For Docker, yes I've noticed they no longer support markdown code blocks, too bad.
